import { Inter } from "next/font/google";
import "./globals.css";
import { T3Provider } from "@/context/T3Provider";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <T3Provider>
          <Navbar />
          {children}
        </T3Provider>
      </body>
    </html>
  );
}
